events {
    worker_connections 1024;
}

http {
    # 1. Redirigir todo el tráfico HTTP (80) a HTTPS (443)
    server {
        listen 80;
        server_name _; # Atrapa cualquier dominio o IP

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # 2. Configuración del servidor HTTPS (443)
    server {
        listen 443 ssl;
        server_name _;

        # Rutas a los certificados que montaremos con Docker
        ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

        # Configuraciones de seguridad SSL básicas
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            # Redirigir el tráfico a tu app Javalin en el puerto 7000
            proxy_pass http://app:7000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}